Configured Workflow Packer Build

diff --git a/ansible/roles/bootstrap/tasks/clevis_bind_usb.yaml b/ansible/roles/bootstrap/tasks/clevis_bind_usb.yaml
--- a/ansible/roles/bootstrap/tasks/clevis_bind_usb.yaml
+++ b/ansible/roles/bootstrap/tasks/clevis_bind_usb.yaml
@@ -101,6 +101,8 @@
       #############################################
       if cryptsetup luksDump "$LUKS_DEV" | grep -qi "clevis"; then
           echo "Clevis keyslot already exists — skipping."
+          echo "Attempting to create marker file: /var/lib/clevis/clevis-enrolled-$LUKS_UUID"
+          touch /var/lib/clevis/clevis-enrolled-$LUKS_UUID || { echo "Failed to create marker file"; exit 1; }
           exit 0
       fi
 
@@ -113,16 +115,9 @@
       echo "Binding Clevis Tang keyslot..."
       clevis luks bind -k "$PASS_PATH" -d "$LUKS_DEV" tang "{\"url\":\"$TANG_URL\"}" -y
 
-      if [[ ! -d /var/lib/clevis ]]; then
-        echo "/var/lib/clevis does not exist!"
-        exit 1
-      fi
-
       echo "Attempting to create marker file: /var/lib/clevis/clevis-enrolled-$LUKS_UUID"
       touch /var/lib/clevis/clevis-enrolled-$LUKS_UUID || { echo "Failed to create marker file"; exit 1; }
-      echo "Marker file created successfully."
 
-      echo "$(date) Clevis bind complete" > /var/lib/clevis/clevis-enrolled-$LUKS_UUID
 
       echo "Clevis bind complete."
       exit 0
